# fly.toml app configuration file generated for l-mesh-server on 2023-10-04T12:25:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "l-mesh-server"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
